# Generated by Django 3.2.9 on 2021-12-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(default='other')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('Priority', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='todo.Category')),
            ],
        ),
    ]
